### ISSUE TITLE
ToDo: Make scatter plots of reanalysis data versus observed data

### ISSUE THREAD

**Issue by ussy6** [ussy6/Radiation#1]
Make XY scatter plots:

- [ ] ERA5 vs Obs (downward shortwave radiation, Abashir, 2021-2024)
- [ ] ERA5 vs Obs (downward longwave radiation, Abashiri, 2021-2024)
- [ ] ERA5 Land vs Obs (downward shortwave radiation, Abashiri, 2021-2024)
- [ ] ERA5 Land vs Obs (downward longwave radiation, Abashiri, 2021-2024)
- [ ] MSM vs Obs (downward shortwave radiation, Abashiri, 2021-2024)
- [ ] MSM vs Obs (downward longwave radiation, Abashiri, 2021-2024)
